//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneApp2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhoneApp2.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Group Name.
        /// </summary>
        public static string AppBarFilterContactsNextButton {
            get {
                return ResourceManager.GetString("AppBarFilterContactsNextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Group.
        /// </summary>
        public static string AppBarSetGroupName {
            get {
                return ResourceManager.GetString("AppBarSetGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS Composer.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CreateGroupText {
            get {
                return ResourceManager.GetString("CreateGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE selected.
        /// </summary>
        public static string DeleteGroups {
            get {
                return ResourceManager.GetString("DeleteGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Filters.
        /// </summary>
        public static string FilterButtonText {
            get {
                return ResourceManager.GetString("FilterButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains .
        /// </summary>
        public static string FilterContainsText {
            get {
                return ResourceManager.GetString("FilterContainsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FilterContainsTextTR {
            get {
                return ResourceManager.GetString("FilterContainsTextTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ends with .
        /// </summary>
        public static string FilterEndsWithText {
            get {
                return ResourceManager.GetString("FilterEndsWithText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FilterEndsWithTextTR {
            get {
                return ResourceManager.GetString("FilterEndsWithTextTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include international contacts.
        /// </summary>
        public static string FilterInternationalText {
            get {
                return ResourceManager.GetString("FilterInternationalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact&apos;s numbers starting .
        /// </summary>
        public static string FilterNumbersStarting {
            get {
                return ResourceManager.GetString("FilterNumbersStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts with .
        /// </summary>
        public static string FilterStartsWithText {
            get {
                return ResourceManager.GetString("FilterStartsWithText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FilterStartsWithTextTR {
            get {
                return ResourceManager.GetString("FilterStartsWithTextTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No match! Please check your filters..
        /// </summary>
        public static string FiltersWarningMessage {
            get {
                return ResourceManager.GetString("FiltersWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Selected Contacts:.
        /// </summary>
        public static string FilterTotalContactsCount {
            get {
                return ResourceManager.GetString("FilterTotalContactsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compose.
        /// </summary>
        public static string MainPageOK {
            get {
                return ResourceManager.GetString("MainPageOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string PhoneNumberTypeCompany {
            get {
                return ResourceManager.GetString("PhoneNumberTypeCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string PhoneNumberTypeHome {
            get {
                return ResourceManager.GetString("PhoneNumberTypeHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Fax.
        /// </summary>
        public static string PhoneNumberTypeHomeFax {
            get {
                return ResourceManager.GetString("PhoneNumberTypeHomeFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell.
        /// </summary>
        public static string PhoneNumberTypeMobile {
            get {
                return ResourceManager.GetString("PhoneNumberTypeMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pager.
        /// </summary>
        public static string PhoneNumberTypePager {
            get {
                return ResourceManager.GetString("PhoneNumberTypePager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work.
        /// </summary>
        public static string PhoneNumberTypeWork {
            get {
                return ResourceManager.GetString("PhoneNumberTypeWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Fax.
        /// </summary>
        public static string PhoneNumberTypeWorkFax {
            get {
                return ResourceManager.GetString("PhoneNumberTypeWorkFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string SelectGroups {
            get {
                return ResourceManager.GetString("SelectGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select None.
        /// </summary>
        public static string SelectNone {
            get {
                return ResourceManager.GetString("SelectNone", resourceCulture);
            }
        }
    }
}
